import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import TopNav from "./_components/topnav";
import "@uploadthing/react/styles.css";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "~/components/ui/sonner";
import { CSPostHogProvider } from "./_analytics/provider";
import { dark } from "@clerk/themes";
import BottomNav from "./_components/bottomnav";
import { ThemeProvider, useTheme } from "next-themes";

export const metadata: Metadata = {
  title: "zerotoprod",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children: children,
  drawer: drawer,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <CSPostHogProvider>
        <html lang="en" className={`${GeistSans.variable}`}>
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          <body className="antialiased">
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              {/* <div className="grid h-screen grid-rows-[auto,1fr]"> */}
              <TopNav />
              <main className="flex items-center justify-center">
                {children}
              </main>
              {drawer}
              {/* </div> */}
              {/* {modal} */}
              {/* <div id="modal-root" /> */}
              {/* <div id="drawer-root" /> */}
              <Toaster />
              <BottomNav />
            </ThemeProvider>
          </body>
        </html>
      </CSPostHogProvider>
    </ClerkProvider>
  );
}
