import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkLoaded, ClerkLoading, ClerkProvider, SignedIn, SignedOut, SignInButton } from "@clerk/nextjs";
import TopNav from "./_components/topnav";

export const metadata: Metadata = {
  title: "zerotoprod",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable} flex flex-col gap-4`}>
        <body>
          <SignedIn>
            <TopNav />
            {children}
          </SignedIn>
          <SignedOut>
            <SignInButton></SignInButton>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
